### ISSUE TITLE
在线浏览问题

### ISSUE THREAD

**Issue by nozomileng** [hvjg2578/CFDL-Drive#1]
竖屏视频太长会显示不全让滚动，jpg文件显示不出，jpeg文件直接下载不显示
![_SOC0U%_{F9SY1`ZH0{0@0R](https://user-images.githubusercontent.com/51223245/130612407-f0bcde9a-e489-4c9b-ac79-f670a85992f0.png)
![W%9PG%4H}ZD$NFOPP TMNAG](https://user-images.githubusercontent.com/51223245/130612416-17662b23-e209-4038-9e7b-84041d8b0915.png)

**Comment by nozomileng** [comment]
png也是直接下载并且显示未发现文件

**Comment by nozomileng** [comment]
并且放子目录好像会出现浏览问题  根目录不存在  在根目录加载过然后再去子目录看就可以

**Comment by hvjg2578** [comment]
你好，关于你所提出的问题，我已经进行了修复，你可以重新下载仓库里面的function.php和media.php并替换原来的文件，然后重新修改Nginx伪静态规则如下：
if (!-f $request_filename)
{
     rewrite '^(.*)$' /index.php?f=$1;
}
if (-f $request_filename)
{
     
}

感谢支持！

**Comment by hvjg2578** [comment]
> 
> 
> 并且放子目录好像会出现浏览问题 根目录不存在 在根目录加载过然后再去子目录看就可以

你好，关于你所提出的问题，我已经进行了修复，你可以重新下载仓库里面的function.php和media.php并替换原来的文件，然后重新修改Nginx伪静态规则如下：
if (!-f $request_filename)
{
rewrite '^(.*)$' /index.php?f=$1;
}
if (-f $request_filename)
{

}

感谢支持！

**Comment by nozomileng** [comment]
图片格式还是无法查看

**Comment by nozomileng** [comment]
添加伪静态后会直接404
![FVO9S$UKQZIZ{3Y3VTF~6YS](https://user-images.githubusercontent.com/51223245/130746502-80be079b-c452-4e26-ab10-9dddec7fa9cc.png)
![FD)(_WH{{5B$Z~7$OXJ~@7](https://user-images.githubusercontent.com/51223245/130746507-7a1ed28d-6450-4dff-bec1-539225bfb473.png)

**Comment by nozomileng** [comment]
放再子目录，主页打开正常，打开文件就会更改
比如文件位置是xxxx.com/xx/，访问能打开但是打开文件就会变成xxxx.com/文件，然后出错

**Comment by nozomileng** [comment]
而且能否直接在窗口比率缩放铺，而不是原比例，导致文件过大要滚动才能看完

**Comment by hvjg2578** [comment]
你试试重新clone一次仓库，我这边问题没有复现，你的PHP版本是多少，我在php7.4和PHP8.0下测试，没有打不开的问题出现，你把出现问题的图片发出来我试一下看看能不能打开

**Comment by hvjg2578** [comment]
窗口比例铺平的问题，我会抽时间进行更改

**Comment by nozomileng** [comment]
php7.4 nginx1.20.1  宝塔安装  开启伪静态 根目录下暂时只知道 发现图片名字出现的问题 **出现部分符号  比如#  %** 这种名字就打不开像其他字母 数字 汉字就能打开

**Comment by nozomileng** [comment]
并且文件放二级目录还是有问题   不添加伪静态打不开文件，添加了伪静态直接404，而且在二级目录打开文件在跳转到一级目录下，手动添加二级目录地址一样是打不开
![image](https://user-images.githubusercontent.com/51223245/131208088-2a1ff78e-284f-4a7d-baa9-9bc1ca5510aa.png)
![image](https://user-images.githubusercontent.com/51223245/131208100-7eed7e26-97af-4b46-be87-9afa5b945593.png)
![image](https://user-images.githubusercontent.com/51223245/131208116-9636f19e-fbc3-462f-8e8c-43e54047ade7.png)
![image](https://user-images.githubusercontent.com/51223245/131208149-dd822392-5a9c-41c0-a084-97bc8ccbfab5.png)

**Comment by hvjg2578** [comment]
关于部分因特殊字符导致无法预览和下载的问题，经查证是url编解码的问题，此问题现已经修复，感谢你的BUG反馈

**Comment by hvjg2578** [comment]
请重新替换仓库中的media.php和function.php，即可修复此问题

**Comment by hvjg2578** [comment]
你可以重新clone一次仓库文件以解决此问题，关于图片显示，我在后续更新中会加入图片灯箱，谢谢

**Comment by hvjg2578** [comment]
如果问题已经解决，麻烦您回复一下，我好确认问题是否修复

**Comment by nozomileng** [comment]
存放根目录没问题了，但是二级目录还是和上面一样https://github.com/hvjg2578/CFDL-Drive/issues/1#issuecomment-907577389

**Comment by hvjg2578** [comment]
很抱歉因为软件BUG给您的使用体验造成了问题，但是我现在是一名高三学生，正在准备2022年高考，暑假开学之后，我可能暂时没有时间去修复这些问题，也麻烦您提供一下具体的设置和文件夹和文件名称，便于我在未来进行问题修复，谢谢你

**Comment by hvjg2578** [comment]
伪静态里面你需要在config.php中把相应的rewrite选项改为true

**Comment by hvjg2578** [comment]
您长时间不回复，issues将会被关闭
